-- MySQL Script generated by MySQL Workbench
-- Mon Nov  5 03:14:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Proyecto2DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Proyecto2DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto2DB` DEFAULT CHARACTER SET utf8 ;
USE `Proyecto2DB` ;

-- -----------------------------------------------------
-- Table `Proyecto2DB`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`Provincia` (
  `idProvincia` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2DB`.`Canton`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`Canton` (
  `idCanton` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCanton`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2DB`.`Distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`Distrito` (
  `idDistrito` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDistrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2DB`.`RolAfectado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`RolAfectado` (
  `idRolAfectado` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRolAfectado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2DB`.`TipoLesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`TipoLesion` (
  `idTipoLesion` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoLesion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2DB`.`EdadQuinquenal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`EdadQuinquenal` (
  `idEdadQuinquenal` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idEdadQuinquenal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2DB`.`Accidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`Accidente` (
  `idAccidente` INT NOT NULL,
  `idProvincia` INT NOT NULL,
  `idCanton` INT NOT NULL,
  `idDistrito` INT NOT NULL,
  `Dia` VARCHAR(45) NOT NULL,
  `Mes` VARCHAR(45) NOT NULL,
  `Anno` VARCHAR(45) NOT NULL,
  `idRolAfectado` INT NOT NULL,
  `idTipoLesion` INT NOT NULL,
  `edadAfectado` VARCHAR(20) NOT NULL,
  `idEdadQuinquenal` INT NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAccidente`),
  INDEX `fk_provincia_idx` (`idProvincia` ASC) VISIBLE,
  INDEX `fk_canton_idx` (`idCanton` ASC) VISIBLE,
  INDEX `fk_distrito_idx` (`idDistrito` ASC) VISIBLE,
  INDEX `fk_tipo_lesion_idx` (`idTipoLesion` ASC) VISIBLE,
  INDEX `fk_rol_afectado_idx` (`idRolAfectado` ASC) VISIBLE,
  INDEX `fk_edad_quinquenal_idx` (`idEdadQuinquenal` ASC) VISIBLE,
  CONSTRAINT `fk_provincia`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `Proyecto2DB`.`Provincia` (`idProvincia`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_canton`
    FOREIGN KEY (`idCanton`)
    REFERENCES `Proyecto2DB`.`Canton` (`idCanton`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_distrito`
    FOREIGN KEY (`idDistrito`)
    REFERENCES `Proyecto2DB`.`Distrito` (`idDistrito`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_tipo_lesion`
    FOREIGN KEY (`idTipoLesion`)
    REFERENCES `Proyecto2DB`.`TipoLesion` (`idTipoLesion`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_rol_afectado`
    FOREIGN KEY (`idRolAfectado`)
    REFERENCES `Proyecto2DB`.`RolAfectado` (`idRolAfectado`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_edad_quinquenal`
    FOREIGN KEY (`idEdadQuinquenal`)
    REFERENCES `Proyecto2DB`.`EdadQuinquenal` (`idEdadQuinquenal`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select a.idAccidente, p.nombre, c.nombre, d.nombre, a.dia, a.mes, a.anno, r.descripcion, t.descripcion, a.edadafectado, e.descripcion, a.sexo
from accidente a,provincia p,distrito d ,canton c,tipolesion t ,edadquinquenal e ,rolafectado r
where a.idProvincia = 1 and a.idProvincia = p.idProvincia and a.idcanton = c.idcanton and d.iddistrito = a.iddistrito and a.idrolafectado = r.idrolafectado and a.idtipolesion = t.idtipolesion and a.idedadquinquenal = e.idedadquinquenal
