-- MySQL Script generated by MySQL Workbench
-- Sun Nov 18 22:14:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Proyecto2DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Proyecto2DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto2DB` DEFAULT CHARACTER SET utf8 ;
USE `Proyecto2DB` ;

-- -----------------------------------------------------
-- Table `Proyecto2DB`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`Provincia` (
  `idProvincia` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2DB`.`Canton`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`Canton` (
  `idCanton` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCanton`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2DB`.`Distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`Distrito` (
  `idDistrito` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDistrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2DB`.`RolAfectado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`RolAfectado` (
  `idRolAfectado` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRolAfectado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2DB`.`TipoLesion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`TipoLesion` (
  `idTipoLesion` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoLesion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2DB`.`EdadQuinquenal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`EdadQuinquenal` (
  `idEdadQuinquenal` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idEdadQuinquenal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2DB`.`Ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`Ubicacion` (
  `idUbicacion` INT NOT NULL,
  `idProvincia` INT NOT NULL,
  `idCanton` INT NOT NULL,
  `idDistrito` INT NOT NULL,
  `Latitud` DECIMAL(40,20) NOT NULL,
  `Longitud` DECIMAL(40,20) NOT NULL,
  PRIMARY KEY (`idUbicacion`),
  INDEX `fk_provincia_ubicacion_idx` (`idProvincia` ASC) VISIBLE,
  INDEX `fk_canton_ubicacion_idx` (`idCanton` ASC) VISIBLE,
  INDEX `fk_distrito_ubicacion_idx` (`idDistrito` ASC) VISIBLE,
  CONSTRAINT `fk_provincia_ubicacion`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `Proyecto2DB`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_canton_ubicacion`
    FOREIGN KEY (`idCanton`)
    REFERENCES `Proyecto2DB`.`Canton` (`idCanton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_distrito_ubicacion`
    FOREIGN KEY (`idDistrito`)
    REFERENCES `Proyecto2DB`.`Distrito` (`idDistrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto2DB`.`Accidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto2DB`.`Accidente` (
  `idAccidente` INT NOT NULL,
  `idUbicacion` INT NOT NULL,
  `Dia` VARCHAR(45) NOT NULL,
  `Mes` VARCHAR(45) NOT NULL,
  `Anno` VARCHAR(45) NOT NULL,
  `idRolAfectado` INT NOT NULL,
  `idTipoLesion` INT NOT NULL,
  `edadAfectado` VARCHAR(20) NOT NULL,
  `idEdadQuinquenal` INT NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAccidente`),
  INDEX `fk_tipo_lesion_idx` (`idTipoLesion` ASC) VISIBLE,
  INDEX `fk_rol_afectado_idx` (`idRolAfectado` ASC) VISIBLE,
  INDEX `fk_edad_quinquenal_idx` (`idEdadQuinquenal` ASC) VISIBLE,
  INDEX `fk_ubicacion_accidente_idx` (`idUbicacion` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_lesion_accidente`
    FOREIGN KEY (`idTipoLesion`)
    REFERENCES `Proyecto2DB`.`TipoLesion` (`idTipoLesion`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_rol_afectado_accidente`
    FOREIGN KEY (`idRolAfectado`)
    REFERENCES `Proyecto2DB`.`RolAfectado` (`idRolAfectado`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_edad_quinquenal_accidente`
    FOREIGN KEY (`idEdadQuinquenal`)
    REFERENCES `Proyecto2DB`.`EdadQuinquenal` (`idEdadQuinquenal`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_ubicacion_accidente`
    FOREIGN KEY (`idUbicacion`)
    REFERENCES `Proyecto2DB`.`Ubicacion` (`idUbicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 
        'root';
        
update edadquinquenal
set descripcion = "De 05 a 9 años"
where idEdadquinquenal = 16;








